# Generated by Django 4.1.6 on 2023-06-16 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetailType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='NoName', max_length=50, verbose_name='Detail')),
            ],
        ),
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveIntegerField(default=0, verbose_name='Detail Level')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.detailtype')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('clutch', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='car_clutch', to='main.detail')),
                ('ecu', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='car_ecu', to='main.detail')),
                ('engine', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='car_engine', to='main.detail')),
                ('turbo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='car_turbo', to='main.detail')),
            ],
        ),
    ]
