# Generated by Django 4.1.6 on 2023-06-17 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_car_clutch_alter_car_ecu_alter_car_engine_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='in_car',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='main.car'),
            preserve_default=False,
        ),
    ]
