# Generated by Django 4.1.6 on 2023-06-17 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_detailtype_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='level',
            field=models.PositiveIntegerField(default=1, verbose_name='Detail Level'),
        ),
    ]
