# Generated by Django 4.1.6 on 2023-06-19 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_car_color_car_image_car_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='acceleration',
            field=models.PositiveIntegerField(default=0, verbose_name='Acceleration'),
        ),
        migrations.AddField(
            model_name='car',
            name='controllability',
            field=models.PositiveIntegerField(default=0, verbose_name='Controllability'),
        ),
        migrations.AddField(
            model_name='car',
            name='max_speed',
            field=models.PositiveIntegerField(default=0, verbose_name='Max Speed'),
        ),
        migrations.AddField(
            model_name='car',
            name='power',
            field=models.PositiveIntegerField(default=0, verbose_name='Power'),
        ),
        migrations.CreateModel(
            name='DealerDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveBigIntegerField(verbose_name='Detail Price')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.detail')),
            ],
        ),
        migrations.CreateModel(
            name='DealerCars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveBigIntegerField(verbose_name='Car Price')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.car')),
            ],
        ),
    ]
