# Generated by Django 4.1.6 on 2023-06-19 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_car_acceleration_car_controllability_car_max_speed_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DealerCars',
            new_name='DealerCar',
        ),
        migrations.RenameModel(
            old_name='DealerDetails',
            new_name='DealerDetail',
        ),
    ]
