# Generated by Django 4.1.6 on 2023-06-19 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_rename_dealercars_dealercar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dealercar',
            name='price',
        ),
        migrations.RemoveField(
            model_name='dealerdetail',
            name='price',
        ),
    ]
