# Generated by Django 4.1.6 on 2023-06-19 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_dealercar_price_remove_dealerdetail_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='price',
            field=models.PositiveBigIntegerField(default=0, verbose_name='Detail Price'),
        ),
    ]
