# Generated by Django 4.1.6 on 2023-06-19 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_detail_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealercar',
            name='count',
            field=models.PositiveBigIntegerField(default=0, verbose_name='Product Count'),
        ),
        migrations.AddField(
            model_name='dealerdetail',
            name='count',
            field=models.PositiveBigIntegerField(default=0, verbose_name='Product Count'),
        ),
    ]
