# Generated by Django 4.1.6 on 2023-06-20 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_dealercar_count_dealerdetail_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='units_added',
            field=models.PositiveIntegerField(default=0, verbose_name='Units Added'),
        ),
    ]
