# Generated by Django 4.1.6 on 2023-06-20 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_detail_units_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detail',
            name='units_added',
        ),
        migrations.AddField(
            model_name='detail',
            name='added_acceleration',
            field=models.PositiveIntegerField(default=0, verbose_name='Added acceleration'),
        ),
        migrations.AddField(
            model_name='detail',
            name='added_controllability',
            field=models.PositiveIntegerField(default=0, verbose_name='Added controllability'),
        ),
        migrations.AddField(
            model_name='detail',
            name='added_max_speed',
            field=models.PositiveIntegerField(default=0, verbose_name='Added max speed'),
        ),
        migrations.AddField(
            model_name='detail',
            name='added_power',
            field=models.PositiveIntegerField(default=0, verbose_name='Added power'),
        ),
    ]
