# Generated by Django 4.1.6 on 2023-06-24 20:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0016_autobazaarcar_owner_autobazaardetail_owner'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AutobazaarDetail',
            new_name='AutoMarketCar',
        ),
        migrations.RenameModel(
            old_name='AutobazaarCar',
            new_name='AutoMarketDetail',
        ),
        migrations.AlterField(
            model_name='automarketcar',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.car'),
        ),
        migrations.AlterField(
            model_name='automarketdetail',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.detail'),
        ),
    ]
